export default {
    footerColor: '#ffffff',
    firH4: 'About this site',
    firH4Color: '#54545c',
    firH4Size: '16px',
    firSpan1: 'Site Link 1',
    firSpan2: 'Site Link 2',
    secH4: 'Get help',
    secH4Color: '#54545c',
    secH4Size: '16px',
    phone: '888-888-8888',
    mail: 'Support@email.com',
    fax: 'Fax: 777-777-7777',
    thrH4: 'Stay in touch',
    thrH4Color: '#54545c',
    thrH4Size: '16px',
    hr: '1px',
    fbLink: 'https://www.facebook.com/WeAreAlluma/?ref=page_internal',
    twLink: 'https://twitter.com/WeAreAlluma',
    inLink: 'https://www.linkedin.com/company/we-are-alluma/',
    fLogoAlt: 'Alluma Logo',
    fLogoWidth: '232',
    fLogoLink: 'https://www.alluma.org/',
    copyrg: 'Copyright 2019',
    pPolicy: 'Privacy Policy',
    ndPolicy: 'Non-discrimination Policy',
    termsOfUse: 'Terms of Use'
}